### ISSUE TITLE
react version

### ISSUE THREAD

**Issue by xavierfuentes** [lukejacksonn/GreedyNav#15]
Has anybody tried to port this to React? I'm having issues doing it so. My main concern is: measuring the DOM elements has to be done on `componentDidMount` but what if a stylesheet (remote with link tag) is affecting the sizes of the menu elements? How do we know when a CSS has been applied to the DOM in componentDidMount?

**Comment by lukejacksonn** [comment]
Good question! I personally, have not tried porting it to react. In principal it should work. The edge case you are talking about is not covered by this implementation either. I am not that interested in solving the problem of "know when a CSS has been applied to the DOM" as this is way out of the scope of this project.

That said.. one approach I would recommend taking (which would solve the issue you are talking about, amongst others) is to use inline styles or some CSS-in-JS library. Doing so would override any global CSS rules and would also mean that anytime the styles/classname was updated, then `shouldComponentUpdate` would fire and re-measuring of the elements could be done.

Just an idea, first thing that came to mind, let me know what you think!

**Comment by xavierfuentes** [comment]
@lukejacksonn thanks for replying that fast! I'm not sure I understand your suggestion, you mean just adding an inline style tag to the `GreedyMenu` component? and wait until an external change would magically make `componentDidUpdate` change? Sorry, I don't understand what you mean

**Comment by lukejacksonn** [comment]
If the only way to style the component was through props like..
```js
<GreedyNav padding="1rem" />
```
for example, then every time that prop changed.. you would know about it right (and you could do re-measuring of the elements)? I don't know the exact ins and outs of react to tell you which lifecycle hooks to use but you should be able to _do something_ when a certain prop changes.

**Comment by xavierfuentes** [comment]
I started working on the react version of a greedy menu [here](https://github.com/xavifuefer/greedy-menu) feedback is very much appreciated!!! 👍
