### ISSUE TITLE
How to not count submenus items

### ISSUE THREAD

**Issue by ljuboja** [lukejacksonn/GreedyNav#3]
Hi, i posted this to codepen also. I hope is ok to post here too. 
I want to use this nav with submenus, but not to count them in counter. Is it possible?
Tnx

**Comment by lukejacksonn** [comment]
Hey, I hop you found the answer to this.. but if you did not then this can be achieved by editing the styles at `line 35` in `greedynav.css`. There the content of the count pseudo element is set `content:attr(count);` . Remove that line or add `display:none` to that selector.
