### ISSUE TITLE
Incorrect resizing when the window is maximized

### ISSUE THREAD

**Issue by ghost** [lukejacksonn/GreedyNav#8]
Hello,

Great project!

I noticed one issue though, and maybe it would be easier to explain it by just mentioning how to reproduce it: 

1) Open a site which uses GreedyNav (even the examples will do, http://codepen.io/lukejacksonn/pen/BowbWE )
2) Resize down the browser window. Greedy nav starts to correctly hide items
3) Once several items are hidden, maximize the browser window.

Expected behavior:
All items in the navigation bar are now correctly displayed, as the window is maximized.

Actual behavior:
The navbar seems to update at some intermediary state, as only part of the navigation items are visible after the window was maximized, while others are still hidden. 

Screenshot (1080x1920 monitor, full screen):

![image](https://cloud.githubusercontent.com/assets/4135636/15514179/7e049d90-21f0-11e6-945c-b3ee2f6924ac.png)

I assume it happens because the resize listener fires off in a weird way when a maximize is being performed, however I'm not a web dev so I don't know how to fix it myself in order to submit a pull request. 

Kind regards,
CataJ

**Comment by ulfmaier** [comment]
There is a recursive call missing. After removing an element check() is called to check if more elements need to be removed. After adding an element this is not happening.

Add check(); in greedynav.js after L41 and it works.

**Comment by lukejacksonn** [comment]
Fixed by https://github.com/lukejacksonn/GreedyNav/pull/9
